#!/usr/bin/python2.5

from os import makedirs, chdir, environ
from os.path import join, expanduser

version = "<unknown>" # set during packaging 
service = "fitness" # set during packaging
environ["FITNESS_VERSION"] = version
environ["FITNESS_SERVICE"] = service

home = expanduser(join("~", ".fitness"))
try:
    makedirs(home)
except:
    pass
chdir(home)
import fitness.fitness
fitgness.fitness.main()

