#!/usr/bin/python2.5

from os import makedirs, chdir, environ
from os.path import join, expanduser

version = "<unknown>" # set during packaging 
environ["FITNESS_VERSION"] = version

home = expanduser(join("~", ".fitness"))
try:
    makedirs(home)
except:
    pass
chdir(home)
import fitness.fitness
